assets:
  - ticker: TSLA
    name: Tesla
    asset_type: stock
    region: US
    currency: USD
    sector: Consumer Cyclical
    cik: "0001318605"

  - ticker: NVDA
    name: Nvidia
    asset_type: stock
    region: US
    currency: USD
    sector: Technology
    cik: "0001045810"

  - ticker: PLTR
    name: Palantir
    asset_type: stock
    region: US
    currency: USD
    sector: Technology
    cik: "0001321655"

  - ticker: AMD
    name: Advanced Micro Devices
    asset_type: stock
    region: US
    currency: USD
    sector: Technology
    cik: "0000002488"

  - ticker: SIE.DE
    name: Siemens
    asset_type: stock
    region: Germany
    currency: EUR
    sector: Industrials

  - ticker: ENR.DE
    name: Siemens Energy
    asset_type: stock
    region: Germany
    currency: EUR
    sector: Energy

  - ticker: RHM.DE
    name: Rheinmetall
    asset_type: stock
    region: Germany
    currency: EUR
    sector: Industrials

  - ticker: SAP.DE
    name: SAP
    asset_type: stock
    region: Germany
    currency: EUR
    sector: Technology